language: go

notifications:
  email: false

env:
  global:
    - secure: "jBsIkCGT1ulgSfYtAWVIT1oBmXGPmUsW8OgqZo+H6qDX5HJopfn0rVzzJFQZoqZwYhYF7kB+7khHXtMrPGezDUUSjoVwluN9VbK6vbAsu89h6SsMGadlyzZisbcjkIcaNwQU5oyzg0VyMc41DO1rXYO91FncAs02KOp0yslIugk="
    - PATH=$HOME/gopath/bin:$PATH

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get golang.org/x/tools/cmd/goimports
  - go get golang.org/x/tools/cmd/vet
  - go get golang.org/x/lint/golint
  - go get github.com/mattn/goveralls

install:
  - go get ./...

before_script:
  - wget https://gist.github.com/mewmew/379014c9a2e6885e238d/raw/goclean.sh
  - chmod +x goclean.sh

script:
  - ./goclean.sh
